require('dotenv').config();
const mongoose = require('mongoose');
const { Achievement } = require('../models/Achievement');

const ACHIEVEMENTS = [
  // ── Steps ─────────────────────────────────────────────────────────────────
  {
    key: 'steps_first_1k',
    category: 'steps',
    icon: 'walk-outline',
    title: 'Baby Steps',
    description: 'Walk 1,000 steps in a day',
  },
  {
    key: 'steps_5k_day',
    category: 'steps',
    icon: 'footsteps-outline',
    title: 'Five Thousand Strong',
    description: 'Walk 5,000 steps in a day',
  },
  {
    key: 'steps_10k_day',
    category: 'steps',
    icon: 'footsteps-outline',
    title: 'Daily Dasher',
    description: 'Reach 10,000 steps in a single day',
  },
  {
    key: 'steps_15k_day',
    category: 'steps',
    icon: 'footsteps-outline',
    title: 'Overachiever',
    description: 'Walk 15,000 steps in a day',
  },
  {
    key: 'steps_20k_day',
    category: 'steps',
    icon: 'flash-outline',
    title: 'Turbo Walker',
    description: 'Walk 20,000 steps in a single day',
  },
  {
    key: 'steps_25k_day',
    category: 'steps',
    icon: 'flash-outline',
    title: 'Step Machine',
    description: 'Walk 25,000 steps in a single day',
  },
  {
    key: 'steps_30k_day',
    category: 'steps',
    icon: 'rocket-outline',
    title: 'Unstoppable Force',
    description: 'Walk 30,000 steps in a single day',
  },
  {
    key: 'steps_50k_day',
    category: 'steps',
    icon: 'rocket-outline',
    title: 'Legend of the Day',
    description: 'Walk 50,000 steps in a single day',
  },
  {
    key: 'steps_total_10k',
    category: 'steps',
    icon: 'walk-outline',
    title: 'Getting Started',
    description: 'Accumulate 10,000 total steps',
  },
  {
    key: 'steps_total_50k',
    category: 'steps',
    icon: 'walk-outline',
    title: 'Warm Up Done',
    description: 'Accumulate 50,000 total steps',
  },
  {
    key: 'steps_total_100k',
    category: 'steps',
    icon: 'footsteps-outline',
    title: 'Century Club',
    description: 'Accumulate 100,000 total steps',
  },
  {
    key: 'steps_total_250k',
    category: 'steps',
    icon: 'footsteps-outline',
    title: 'Quarter Million',
    description: 'Accumulate 250,000 total steps',
  },
  {
    key: 'steps_total_500k',
    category: 'steps',
    icon: 'ribbon-outline',
    title: 'Half a Million',
    description: 'Accumulate 500,000 total steps',
  },
  {
    key: 'steps_total_1m',
    category: 'steps',
    icon: 'star-outline',
    title: 'Million Mover',
    description: 'Accumulate 1,000,000 total steps',
  },
  {
    key: 'steps_total_2m',
    category: 'steps',
    icon: 'star-outline',
    title: 'Double Million',
    description: 'Accumulate 2,000,000 total steps',
  },
  {
    key: 'steps_total_5m',
    category: 'steps',
    icon: 'trophy-outline',
    title: 'Five Million Club',
    description: 'Accumulate 5,000,000 total steps',
  },
  {
    key: 'steps_total_10m',
    category: 'steps',
    icon: 'trophy-outline',
    title: 'Ten Million Steps',
    description: 'Accumulate 10,000,000 total steps',
  },
  {
    key: 'steps_marathon',
    category: 'steps',
    icon: 'ribbon-outline',
    title: 'Marathon Walker',
    description: 'Walk a marathon distance (~56,000 steps)',
  },
  {
    key: 'steps_ultra',
    category: 'steps',
    icon: 'ribbon-outline',
    title: 'Ultramarathon',
    description: 'Walk 100km worth of steps in a week (~133,000)',
  },
  {
    key: 'steps_week_70k',
    category: 'steps',
    icon: 'calendar-outline',
    title: 'Perfect Week',
    description: 'Walk 70,000 steps in a single week',
  },
  {
    key: 'steps_week_100k',
    category: 'steps',
    icon: 'calendar-outline',
    title: 'Centurion Week',
    description: 'Walk 100,000 steps in a single week',
  },
  {
    key: 'steps_month_300k',
    category: 'steps',
    icon: 'calendar-outline',
    title: 'Monthly Grinder',
    description: 'Walk 300,000 steps in a single month',
  },
  {
    key: 'steps_month_500k',
    category: 'steps',
    icon: 'calendar-outline',
    title: 'Monthly Machine',
    description: 'Walk 500,000 steps in a single month',
  },
  {
    key: 'steps_early_bird',
    category: 'steps',
    icon: 'sunny-outline',
    title: 'Early Bird',
    description: 'Log 5,000 steps before 8am',
  },
  {
    key: 'steps_night_owl',
    category: 'steps',
    icon: 'moon-outline',
    title: 'Night Owl',
    description: 'Log 5,000 steps after 9pm',
  },

  // ── Streaks ───────────────────────────────────────────────────────────────
  {
    key: 'streak_3',
    category: 'streaks',
    icon: 'flame-outline',
    title: 'Just Getting Started',
    description: '3-day activity streak',
  },
  {
    key: 'streak_5',
    category: 'streaks',
    icon: 'flame-outline',
    title: 'High Five',
    description: '5-day activity streak',
  },
  {
    key: 'streak_7',
    category: 'streaks',
    icon: 'flame-outline',
    title: 'Week Warrior',
    description: '7-day activity streak',
  },
  {
    key: 'streak_10',
    category: 'streaks',
    icon: 'flame-outline',
    title: 'Ten Day Titan',
    description: '10-day activity streak',
  },
  {
    key: 'streak_14',
    category: 'streaks',
    icon: 'flame-outline',
    title: 'Two-Week Titan',
    description: '14-day activity streak',
  },
  {
    key: 'streak_21',
    category: 'streaks',
    icon: 'thunderstorm-outline',
    title: 'Habit Formed',
    description: '21-day activity streak',
  },
  {
    key: 'streak_30',
    category: 'streaks',
    icon: 'thunderstorm-outline',
    title: 'Monthly Grind',
    description: '30-day activity streak',
  },
  {
    key: 'streak_45',
    category: 'streaks',
    icon: 'thunderstorm-outline',
    title: 'Mid-Season Hero',
    description: '45-day activity streak',
  },
  {
    key: 'streak_60',
    category: 'streaks',
    icon: 'thunderstorm-outline',
    title: 'Two Month Machine',
    description: '60-day activity streak',
  },
  {
    key: 'streak_75',
    category: 'streaks',
    icon: 'star-outline',
    title: 'Relentless',
    description: '75-day activity streak',
  },
  {
    key: 'streak_90',
    category: 'streaks',
    icon: 'star-outline',
    title: 'Quarter Year Strong',
    description: '90-day activity streak',
  },
  {
    key: 'streak_100',
    category: 'streaks',
    icon: 'star-outline',
    title: 'Unstoppable',
    description: '100-day activity streak',
  },
  {
    key: 'streak_150',
    category: 'streaks',
    icon: 'trophy-outline',
    title: 'Half Season Stalwart',
    description: '150-day activity streak',
  },
  {
    key: 'streak_180',
    category: 'streaks',
    icon: 'trophy-outline',
    title: 'Half Year Hero',
    description: '180-day activity streak',
  },
  {
    key: 'streak_365',
    category: 'streaks',
    icon: 'trophy-outline',
    title: 'Full Year Warrior',
    description: '365-day activity streak',
  },
  {
    key: 'streak_weekend',
    category: 'streaks',
    icon: 'calendar-outline',
    title: 'Weekend Warrior',
    description: 'Be active every weekend for a month',
  },
  {
    key: 'streak_comeback',
    category: 'streaks',
    icon: 'refresh-outline',
    title: 'Comeback Kid',
    description: 'Restart a streak after missing a day',
  },
  {
    key: 'streak_no_rest',
    category: 'streaks',
    icon: 'infinite-outline',
    title: 'No Days Off',
    description: 'Be active every day for a full month',
  },
  {
    key: 'streak_morning_7',
    category: 'streaks',
    icon: 'sunny-outline',
    title: 'Rise and Grind',
    description: 'Log steps before 7am for 7 days in a row',
  },

  // ── Wins ──────────────────────────────────────────────────────────────────
  {
    key: 'win_first_complete',
    category: 'wins',
    icon: 'flag-outline',
    title: 'Finisher',
    description: 'Complete your first challenge',
  },
  {
    key: 'win_podium',
    category: 'wins',
    icon: 'podium-outline',
    title: 'Podium Finish',
    description: 'Finish top 3 in any challenge',
  },
  {
    key: 'win_gold',
    category: 'wins',
    icon: 'trophy-outline',
    title: 'Gold Rush',
    description: 'Win 1st place in a challenge',
  },
  {
    key: 'win_silver',
    category: 'wins',
    icon: 'ribbon-outline',
    title: 'Silver Lining',
    description: 'Finish 2nd place in a challenge',
  },
  {
    key: 'win_bronze',
    category: 'wins',
    icon: 'ribbon-outline',
    title: 'Bronze Effort',
    description: 'Finish 3rd place in a challenge',
  },
  {
    key: 'win_top10',
    category: 'wins',
    icon: 'ribbon-outline',
    title: 'Top Ten',
    description: 'Finish in the top 10 of any challenge',
  },
  {
    key: 'win_top25_pct',
    category: 'wins',
    icon: 'ribbon-outline',
    title: 'Upper Echelon',
    description: 'Finish in the top 25% of a challenge',
  },
  {
    key: 'win_hat_trick',
    category: 'wins',
    icon: 'trophy-outline',
    title: 'Hat Trick',
    description: 'Win 3 challenges',
  },
  {
    key: 'win_5_golds',
    category: 'wins',
    icon: 'trophy-outline',
    title: 'Gold Collector',
    description: 'Win 1st place 5 times',
  },
  {
    key: 'win_10_golds',
    category: 'wins',
    icon: 'trophy-outline',
    title: 'Serial Champion',
    description: 'Win 1st place 10 times',
  },
  {
    key: 'win_contender_5',
    category: 'wins',
    icon: 'ribbon-outline',
    title: 'Consistent Contender',
    description: 'Complete 5 challenges',
  },
  {
    key: 'win_contender_10',
    category: 'wins',
    icon: 'ribbon-outline',
    title: 'Dedicated Competitor',
    description: 'Complete 10 challenges',
  },
  {
    key: 'win_contender_25',
    category: 'wins',
    icon: 'ribbon-outline',
    title: 'Challenge Veteran',
    description: 'Complete 25 challenges',
  },
  {
    key: 'win_contender_50',
    category: 'wins',
    icon: 'trophy-outline',
    title: 'Challenge Legend',
    description: 'Complete 50 challenges',
  },
  {
    key: 'win_comeback',
    category: 'wins',
    icon: 'arrow-up-outline',
    title: 'The Comeback',
    description: 'Finish top 10 after being ranked 50+',
  },
  {
    key: 'win_underdog',
    category: 'wins',
    icon: 'flash-outline',
    title: 'Underdog Story',
    description: 'Win a challenge with 50+ participants',
  },
  {
    key: 'win_legend',
    category: 'wins',
    icon: 'star-outline',
    title: 'Legend',
    description: 'Top a leaderboard of 100+ participants',
  },
  {
    key: 'win_100pct',
    category: 'wins',
    icon: 'checkmark-circle',
    title: 'Perfect Score',
    description: 'Hit 100% of the step goal in a challenge',
  },
  {
    key: 'win_early_finish',
    category: 'wins',
    icon: 'timer-outline',
    title: 'Speed Demon',
    description: 'Complete a challenge goal in half the time',
  },
  {
    key: 'win_solo',
    category: 'wins',
    icon: 'person-outline',
    title: 'Solo Artist',
    description: 'Create and complete your own challenge',
  },
  {
    key: 'win_streak_3',
    category: 'wins',
    icon: 'flame-outline',
    title: 'On Fire',
    description: 'Win 3 challenges in a row',
  },
  {
    key: 'win_multi_podium',
    category: 'wins',
    icon: 'podium-outline',
    title: 'Podium Regular',
    description: 'Finish top 3 in 5 different challenges',
  },
  {
    key: 'win_month_champ',
    category: 'wins',
    icon: 'calendar-outline',
    title: 'Month Champion',
    description: 'Win the most steps in a calendar month',
  },

  // ── Social ────────────────────────────────────────────────────────────────
  {
    key: 'social_first_friend',
    category: 'social',
    icon: 'person-add-outline',
    title: 'First Friend',
    description: 'Add your first friend',
  },
  {
    key: 'social_5_friends',
    category: 'social',
    icon: 'people-outline',
    title: 'Squad Goals',
    description: 'Have 5 friends on the app',
  },
  {
    key: 'social_10_friends',
    category: 'social',
    icon: 'people-outline',
    title: 'Social Butterfly',
    description: 'Have 10 friends on the app',
  },
  {
    key: 'social_25_friends',
    category: 'social',
    icon: 'people-outline',
    title: 'Popular Kid',
    description: 'Have 25 friends on the app',
  },
  {
    key: 'social_50_friends',
    category: 'social',
    icon: 'people-circle-outline',
    title: 'Community Builder',
    description: 'Have 50 friends on the app',
  },
  {
    key: 'social_first_group',
    category: 'social',
    icon: 'people-outline',
    title: 'Team Player',
    description: 'Join your first group challenge',
  },
  {
    key: 'social_3_groups',
    category: 'social',
    icon: 'people-outline',
    title: 'Group Hopper',
    description: 'Participate in 3 different group challenges',
  },
  {
    key: 'social_5_groups',
    category: 'social',
    icon: 'people-outline',
    title: 'Group Veteran',
    description: 'Participate in 5 different group challenges',
  },
  {
    key: 'social_10_groups',
    category: 'social',
    icon: 'people-circle-outline',
    title: 'Group Legend',
    description: 'Participate in 10 different group challenges',
  },
  {
    key: 'social_hype_machine',
    category: 'social',
    icon: 'heart-outline',
    title: 'Hype Machine',
    description: 'Be the most active member in a group for a week',
  },
  {
    key: 'social_top_friend',
    category: 'social',
    icon: 'podium-outline',
    title: 'Top of the Pack',
    description: 'Outscore all your friends in a challenge',
  },
  {
    key: 'social_beat_friend',
    category: 'social',
    icon: 'flash-outline',
    title: 'Friendly Rival',
    description: 'Finish above a friend in a challenge',
  },
  {
    key: 'social_invite',
    category: 'social',
    icon: 'share-outline',
    title: 'Recruiter',
    description: 'Invite a friend who then joins the app',
  },
  {
    key: 'social_creator',
    category: 'social',
    icon: 'add-circle-outline',
    title: 'Challenge Creator',
    description: 'Create your first challenge',
  },
  {
    key: 'social_5_created',
    category: 'social',
    icon: 'add-circle-outline',
    title: 'Prolific Creator',
    description: 'Create 5 challenges',
  },
  {
    key: 'social_10_created',
    category: 'social',
    icon: 'add-circle-outline',
    title: 'Challenge Architect',
    description: 'Create 10 challenges',
  },
  {
    key: 'social_big_group',
    category: 'social',
    icon: 'people-circle-outline',
    title: 'Crowd Pleaser',
    description: 'Have 20+ people join a challenge you created',
  },
  {
    key: 'social_ambassador',
    category: 'social',
    icon: 'star-outline',
    title: 'Ambassador',
    description: 'Have 50+ people join a challenge you created',
  },
  {
    key: 'social_sync_day',
    category: 'social',
    icon: 'sync-outline',
    title: 'In Sync',
    description: 'Log steps on the same day as 5 friends',
  },
  {
    key: 'social_consistent',
    category: 'social',
    icon: 'checkmark-circle',
    title: 'Consistently There',
    description: 'Be active in a group challenge every single day',
  },
  {
    key: 'social_motivator',
    category: 'social',
    icon: 'chatbubble-outline',
    title: 'The Motivator',
    description:
      'Have a friend reach their goal after you joined their challenge',
  },
  {
    key: 'social_rival',
    category: 'social',
    icon: 'swap-horizontal-outline',
    title: 'Head to Head',
    description: 'Participate in 3 challenges with the same friend',
  },
  {
    key: 'social_first_win_group',
    category: 'social',
    icon: 'trophy-outline',
    title: 'Group Gold',
    description: 'Win a group challenge',
  },

  {
    key: 'steps_5k_5days',
    category: 'steps',
    icon: 'footsteps-outline',
    title: 'Five for Five',
    description: 'Walk 5,000 steps for 5 days in a row',
  },
  {
    key: 'steps_total_750k',
    category: 'steps',
    icon: 'ribbon-outline',
    title: 'Three Quarter Million',
    description: 'Accumulate 750,000 total steps',
  },
  {
    key: 'steps_total_3m',
    category: 'steps',
    icon: 'star-outline',
    title: 'Three Million Club',
    description: 'Accumulate 3,000,000 total steps',
  },
  {
    key: 'streak_48',
    category: 'streaks',
    icon: 'thunderstorm-outline',
    title: 'Seven Weeks Strong',
    description: '48-day activity streak',
  },
  {
    key: 'win_back_to_back',
    category: 'wins',
    icon: 'trophy-outline',
    title: 'Back to Back',
    description: 'Win 2 challenges in a row',
  },
  {
    key: 'win_top5_pct',
    category: 'wins',
    icon: 'podium-outline',
    title: 'Elite Performer',
    description: 'Finish in the top 5% of a challenge',
  },
  {
    key: 'social_20_friends',
    category: 'social',
    icon: 'people-outline',
    title: 'Network Builder',
    description: 'Have 20 friends on the app',
  },
  {
    key: 'social_both_podium',
    category: 'social',
    icon: 'podium-outline',
    title: 'Dynamic Duo',
    description:
      'Both you and a friend finish in the top 3 of the same challenge',
  },
  {
    key: 'social_all_finish',
    category: 'social',
    icon: 'people-outline',
    title: 'No One Left Behind',
    description: 'Everyone in your group challenge reaches the goal',
  },
];

const seed = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected to MongoDB');

  let created = 0;
  let updated = 0;

  for (const data of ACHIEVEMENTS) {
    const result = await Achievement.findOneAndUpdate({ key: data.key }, data, {
      upsert: true,
      new: true,
      setDefaultsOnInsert: true,
    });
    if (result.createdAt?.getTime() === result.updatedAt?.getTime()) {
      created++;
    } else {
      updated++;
    }
  }

  console.log(
    `✓ ${ACHIEVEMENTS.length} achievements processed — ${created} created, ${updated} updated`,
  );
  await mongoose.disconnect();
  process.exit(0);
};

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
